import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const artifactPath = resolve(root, 'out/Escrow.sol/TrustlessEscrow.json');
const outPath = resolve(root, 'frontend/src/lib/escrow.ts');

const artifact = JSON.parse(readFileSync(artifactPath, 'utf8'));
const abi = JSON.stringify(artifact.abi, null, 2);
const bytecode = artifact.bytecode.object;

const generated = `// Generated by scripts/gen-abi.mjs from out/Escrow.sol/TrustlessEscrow.json. Do not edit.
export const escrowAbi = ${abi} as const;

export const escrowBytecode = '${bytecode}' as const;
`;

writeFileSync(outPath, generated);
console.log('Wrote', outPath);
